name: dcflight
description: "Build Native App UIs with Dart"
version: 0.0.2
homepage: https://github.com/Dotcorr/dcflight
repository: https://github.com/Dotcorr/dcflight

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"
  
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  # framework dependencies (prod)

  # dcf_primitives: ^0.0.1
# framework dependencies (local)
  dcf_primitives:
    path: ../dcf_primitives
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  plugin:
    platforms:
      ios:
        pluginClass: DCFAppDelegate
      

