name: dcflight
description: "Build Native App UIs with Dart"
version: 0.0.2
homepage: https://github.com/Dotcorr/dcflight
repository: https://github.com/Dotcorr/dcflight

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # web_socket_channel: ^3.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  plugin:
    platforms:
      ios:
        pluginClass: DCFAppDelegate
      

